### ISSUE TITLE
Add libtool

### ISSUE THREAD

**Issue by acotty** [arnholm/cpde_3rdparty#2]
I found yesterday that I needed to add libtool on my newly installed Linux Mint 20.3 guest to get the .bootstrap and configure to work.

As such can the following line be added to the script:
_sudo apt install -y libtool_

While you are modifying the script can you also add the following comment so that if the script is downloaded and then passed on then the second developer can find updates:
**#
# Script source : https://github.com/arnholm/cpde_3rdparty/blob/master/gcc/codeblocks/build_cb.sh
#**

Yet another potential update, but this one is not required, but may help newbies with ensuring they are using a recent version of GCC is below. This 
#-------- install GNU GCC 11  --------
#  This should only be done if you need to use GCC 11:
#add-apt-repository ppa:ubuntu-toolchain-r/test  --yes
#apt-get update
#apt-get -y  install cpp-11 gcc-11 g++-11
#
# To use update-alternatives to change the configures GCC version run the following for the different GCC versions installed:
#update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
#update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
#update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
#
# To display and change the default GCC run the following
#update-alternatives --config gcc

BTW I am still working my way through the build process, so there may be more changes once I get the build process working on LM 20.3 and then ensure it is reproduce able by reverting back to the LM 20.3 guest with the updated and gust additions installed only.

**Comment by arnholm** [comment]
I will add libtool as suggested to Code::Blocks **build_cb.sh** although it is clearly not stated that it is what you mean.

If you have multiple suggestions please consider using pull requests
